"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
console.log("Is 5 > 3? True");
console.log(5 > 3);
console.log("Is 2 > 10? False");
console.log(2 > 10);
console.log("Is 'apple' != 'orange'? True");
let fruit1 = "apple";
let fruit2 = "orange";
console.log(fruit1 != fruit2);
console.log("Is 'apple' == 'apple'? True");
let fruit3 = "apple";
let fruit4 = "apple";
console.log(fruit3 == fruit4);
console.log("Is 10 < 5? False");
console.log(10 < 5);
console.log("Is 20 >= 20? True");
console.log(20 >= 20);
console.log("Is 15 <= 14? False");
console.log(15 <= 14);
console.log("Is true && false? False");
console.log(true && false);
//# sourceMappingURL=app.js.map